site_name: nuRemics
site_url: https://nuremics.github.io

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Launch: getting-started/launch.md
    - Exploration: getting-started/exploration.md
  - Handbook:
    - Overview: handbook/index.md
    - Design: handbook/design.md
    - Usability: handbook/usability.md
  - Use Cases:
    - Overview : use-cases/index.md
    - Modeling & Simulation: use-cases/simulation/index.md
    - AI/ML: use-cases/aiml/index.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    scheme: default  # ou 'slate' pour un fond sombre
    primary: teal     # couleur principale (menu, boutons)
    accent: amber     # couleur secondaire (liens, survols)
  font:
    text: Jost       # police du texte
    code: Roboto Mono  # police du code
  features:
    - content.code.copy

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-CW8NJP4DBF